# Generated by Django 3.1.5 on 2021-01-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='state',
            field=models.CharField(choices=[('TD', 'TO DO'), ('DN', 'DONE')], default='TD', max_length=2),
        ),
    ]
